import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Sidebar from "@/app/components/Sidebar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="he">
      <body className={inter.className}>
      <main className="flex flex-col min-h-screen">
          <Navbar/>
          <div id="main" className="flex flex-row flex-grow h-full">
              <Sidebar />
              {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
